[build]
  publish = "dist"
  command = "yarn build"
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
[[plugins]]
package = "@algolia/netlify-plugin-crawler"
  [plugins.inputs]
  renderJavaScript = true