name: Lighthouse CI
on: push
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            https://aaditkamat.me
            https://aaditkamat.me/about
            https://aaditkamat.me/calendar
            https://aaditkamat.me/podcasts
            https://aaditkamat.me/privacy
            https://aaditkamat.me/projects
            https://aaditkamat.me/resume
            https://aaditkamat.me/terms
            https://aaditkamat.me/tools
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
